### ISSUE TITLE
I got some problems while deploying the filedrop-ws at heroku

### ISSUE THREAD

**Issue by prasadbobby** [mat-sz/filedrop-ws#1]
I got some problems while deploying the filedrop-ws at heroku.

Could you please try to write a brief documentation on filedrop-ws like **heroku deployment**.

**Comment by mat-sz** [comment]
Filedrop is available as a Docker-based package: https://github.com/mat-sz/filedrop-docker

Could you try using that? I have no experience with deploying things to Heroku, I have only worked with AWS and Azure before.

**Comment by prasadbobby** [comment]
**_Thank  you for your reply brother_**. But i need deployment without docker. Is there any documentation you have for **filedrop-ws**. In **AWS** which service you are using to deploy the **filedrop-ws**

**Comment by prasadbobby** [comment]
Still Confusing Brother . Please try to help with me

**Comment by mat-sz** [comment]
There's nothing beyond what is described [here](https://github.com/mat-sz/filedrop-web#self-hosting) that I am able to help you with.
